name = "site-blogs"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "../frontend"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "__CLERK_PUBLISHABLE_KEY__"
CLERK_SECRET_KEY = "__CLERK_SECRET_KEY__"
